name: Build & Test Pipeline

# Trigger on every push to main branch
on:
  push:
    branches:
      - main

jobs:
  # Job 1: Run tests
  test-job:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm test

  # Job 2: Build Docker image (only runs if tests pass)
  build-job:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test-job  # This job depends on test-job succeeding
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          echo "✅ Docker image built successfully!"
      
      - name: Verify image was created
        run: docker images | grep my-app